# Generated by Django 5.1.4 on 2025-01-30 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_rename_image_image_user_alter_image_user_options'),
        ('signup_app', '0002_user_is_active_user_is_superviser_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_user',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='signup_app.user'),
        ),
    ]
