# Generated by Django 5.1.4 on 2025-03-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_image_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_user',
            name='classification',
            field=models.CharField(blank=True, choices=[('תיירות', 'תיירות'), ('לא תיירות', 'לא תיירות')], max_length=50, null=True),
        ),
    ]
