# Generated by Django 5.1.4 on 2025-03-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_image_user_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_user',
            name='classification',
        ),
    ]
