# Generated by Django 5.1.4 on 2025-03-04 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_remove_image_user_classification'),
        ('signup_app', '0002_user_is_active_user_is_superviser_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_user',
            name='classification',
            field=models.CharField(choices=[('תיירות', 'תיירות'), ('לא תיירות', 'לא תיירות')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='image_user',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image_user',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='signup_app.user'),
        ),
    ]
