# Generated by Django 5.1.4 on 2025-05-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_image_user_classification_image_user_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_user',
            name='feedback',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10, null=True),
        ),
    ]
